#!/usr/bin/env python3
"""Compute the TeX Live packages each template needs, from a real compile.

latex-forge can set users up with a lightweight TeX distribution (TinyTeX)
that only ships a core set of packages. When a project is created from a
template, latex-forge installs whatever that template still needs — and the
fastest, most reliable way to know what that is, is a ``tex_packages`` list in
the template's ``latexforge.toml``. This script produces that list.

How it works: each template is compiled with ``latexmk -recorder`` (exactly
the ``latex-forge build`` invocation) on a machine with a *full* TeX Live
(scheme-full, as installed in CI). The recorder's ``.fls`` file lists every
file the engine read; each one under TEXMFROOT is mapped back to the TeX Live
package that ships it using the installation's own package database
(``tlpkg/texlive.tlpdb``). Helper programs that don't show up in the ``.fls``
(the engine itself, latexmk, biber/bibtex, makeindex) are added from the
build artefacts they leave behind.

Each template is compiled in a temporary copy, so the working tree is never
polluted with build artefacts.

Run from the repo root:
    python3 scripts/compute_tex_packages.py --only awesome-cv         # print
    python3 scripts/compute_tex_packages.py --category cv --write     # update tomls
    python3 scripts/compute_tex_packages.py --path ~/my-project --main my-project.tex

Exit code 0 = every selected template compiled and got a package list.
Exit code 1 = at least one failed (or a tool was missing).
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).parent.parent
TEMPLATES_DIR = ROOT / "templates"
GALLERY_JSON = ROOT / "gallery.json"

# Mirror latex_forge/build.py: the latexmk flag for each declared engine.
ENGINE_FLAG = {"lualatex": "-lualatex", "xelatex": "-xelatex", "pdflatex": "-pdf"}

# Packages providing the engine binaries and their LaTeX formats. The format
# file itself lives in TEXMFVAR (generated, not shipped by any package), so the
# recorder can't attribute it — hence this explicit table.
ENGINE_PACKAGES = {
    "pdflatex": ["latex-bin", "pdftex"],
    "lualatex": ["latex-bin", "luahbtex", "luatex"],
    "xelatex": ["xetex"],
}

PER_TEMPLATE_TIMEOUT = 300  # seconds (some theses with custom fonts are slow)

# Marker written above the generated list, so --write can replace it later.
GENERATED_COMMENT = (
    "# TeX Live packages this template needs, generated by\n"
    "# latex-forge-gallery/scripts/compute_tex_packages.py — latex-forge installs\n"
    "# the missing ones when a project is created on a lightweight (TinyTeX) setup.\n"
)
# The tex_packages array plus the comment lines right above it.
_EXISTING_BLOCK = re.compile(
    r"(?:^#[^\n]*\n)*^tex_packages\s*=\s*\[[^\]]*\]\s*\n?",
    re.MULTILINE,
)


# ---------------------------------------------------------------------------
# TeX Live package database
# ---------------------------------------------------------------------------

def texmf_root() -> Path:
    out = subprocess.run(
        ["kpsewhich", "-var-value", "TEXMFROOT"],
        capture_output=True, text=True, check=True,
    )
    return Path(out.stdout.strip())


def load_file_index(tlpdb: Path) -> dict[str, str]:
    """Map every runfile path (relative to TEXMFROOT) to its package name.

    Architecture-specific binary packages (``luatex.x86_64-linux``) are
    skipped: what a template needs is the platform-neutral package name, and
    tlmgr pulls in the right binaries for the user's platform itself.
    """
    index: dict[str, str] = {}
    package: str | None = None
    in_runfiles = False
    with tlpdb.open(encoding="utf-8", errors="replace") as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if line.startswith("name "):
                name = line[5:].strip()
                package = None if "." in name else name
                in_runfiles = False
            elif line.startswith("runfiles"):
                in_runfiles = True
            elif line.startswith(" ") and in_runfiles and package:
                # " texmf-dist/tex/latex/foo/foo.sty" (optionally followed by details)
                path = line.strip().split(" ", 1)[0]
                index[path] = package
            elif line and not line.startswith(" "):
                in_runfiles = False
    return index


# ---------------------------------------------------------------------------
# Compiling and attributing
# ---------------------------------------------------------------------------

def latexmk_command(engine: str, main: str) -> list[str]:
    """The exact invocation latex-forge build uses (see latex_forge/build.py)."""
    return [
        "latexmk",
        "-recorder",
        "-synctex=1",
        "-interaction=nonstopmode",
        "-file-line-error",
        ENGINE_FLAG.get(engine, "-lualatex"),
        "-outdir=build",
        main,
    ]


_FONT_SUFFIXES = (".otf", ".ttf", ".ttc", ".pfb")
_BASEFONT = re.compile(rb"/BaseFont\s*/([A-Za-z0-9+\-_.,#]+)")
_STREAM = re.compile(rb"stream\r?\n(.*?)\r?\nendstream", re.DOTALL)
# fontspec logs each face it sets up as an NFSS spec: <->"[EBGaramond-Regular.otf]/OT:..."
_LOG_FONT_FILE = re.compile(r'"\[([^\]"]+\.(?:otf|ttf|ttc))\]', re.IGNORECASE)
# TeX wraps log lines at this many characters.
_LOG_LINE_WIDTH = 79


def _normalise(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "", name.lower())


def pdf_font_names(pdf: Path) -> set[str]:
    """PostScript names of the fonts embedded in *pdf* (subset tags removed).

    LuaTeX and XeTeX load OpenType fonts outside kpathsea's recorder, so the
    .fls misses them; the PDF is the reliable record of what was used. Font
    dictionaries usually sit in compressed object streams, hence the inflate.
    """
    import zlib

    data = pdf.read_bytes()
    chunks = [data]
    for match in _STREAM.finditer(data):
        try:
            chunks.append(zlib.decompress(match.group(1)))
        except zlib.error:
            continue
    names = set()
    for chunk in chunks:
        for raw in _BASEFONT.findall(chunk):
            name = raw.decode("latin-1").split("+", 1)[-1]
            names.add(name)
    return names


def font_packages(font_names: set[str], index: dict[str, str]) -> set[str]:
    """Map embedded font names to the packages shipping a matching font file."""
    fonts: dict[str, list[tuple[str, str]]] = {}
    for path, pkg in index.items():
        if path.lower().endswith(_FONT_SUFFIXES):
            stem = _normalise(path.rsplit("/", 1)[-1].rsplit(".", 1)[0])
            fonts.setdefault(stem[:4], []).append((stem, pkg))

    found = set()
    for name in font_names:
        wanted = _normalise(name)
        candidates = fonts.get(wanted[:4], [])
        exact = [pkg for stem, pkg in candidates if stem == wanted]
        if exact:
            found.add(exact[0])
            continue
        prefixed = sorted((len(stem), pkg) for stem, pkg in candidates if stem.startswith(wanted))
        if prefixed:
            found.add(prefixed[0][1])
    return found


def log_font_files(log: Path) -> set[str]:
    """Font files fontspec set up, by file name, according to the log.

    This catches faces a class declares but the sample document never uses:
    they are absent from the PDF, yet fontspec still opens them when the class
    loads, so they must be installed.
    """
    if not log.exists():
        return set()
    # Undo TeX's hard wrapping so a file name split across lines still matches.
    text = ""
    for line in log.read_text(encoding="utf-8", errors="replace").splitlines():
        text += line if len(line) == _LOG_LINE_WIDTH else line + "\n"
    return {name.rsplit("/", 1)[-1] for name in _LOG_FONT_FILE.findall(text)}


def font_file_packages(files: set[str], index: dict[str, str]) -> set[str]:
    """Map font file names to the packages shipping them."""
    wanted = {name.lower() for name in files}
    return {
        pkg for path, pkg in index.items()
        if path.lower().endswith(_FONT_SUFFIXES) and path.rsplit("/", 1)[-1].lower() in wanted
    }


def packages_from_build(build_dir: Path, stem: str, root: Path,
                        index: dict[str, str], engine: str) -> set[str]:
    """Attribute every file the compile read (per the .fls) to a package."""
    packages = set(ENGINE_PACKAGES.get(engine, [])) | {"latexmk"}
    packages |= font_packages(pdf_font_names(build_dir / f"{stem}.pdf"), index)
    packages |= font_file_packages(log_font_files(build_dir / f"{stem}.log"), index)

    fls = build_dir / f"{stem}.fls"
    root_prefix = str(root.resolve()).rstrip("/") + "/"
    for line in fls.read_text(encoding="utf-8", errors="replace").splitlines():
        if not line.startswith("INPUT "):
            continue
        path = line[6:].strip()
        resolved = str(Path(path).resolve()) if Path(path).is_absolute() else path
        for candidate in (path, resolved):
            if candidate.startswith(root_prefix):
                pkg = index.get(candidate[len(root_prefix):])
                if pkg:
                    packages.add(pkg)
                break

    # Helper programs leave artefacts behind rather than .fls entries.
    if any(build_dir.glob("*.bcf")):
        packages.add("biber")
    aux = build_dir / f"{stem}.aux"
    if aux.exists() and "\\bibdata" in aux.read_text(encoding="utf-8", errors="replace"):
        packages.add("bibtex")
    if any(build_dir.glob("*.idx")):
        packages.add("makeindex")
    if any(build_dir.glob("*.glo")) or any(build_dir.glob("*.acn")):
        packages.add("glossaries")
    return packages


def first_error(log: Path) -> str:
    """The first LaTeX error in *log*, to make a failure actionable in CI."""
    if not log.exists():
        return ""
    lines = log.read_text(encoding="utf-8", errors="replace").splitlines()
    for i, line in enumerate(lines):
        # -file-line-error prints errors as "./file.tex:12: message"; package
        # errors continue on the next lines.
        if line.startswith("! ") or re.match(r"^\.?/?[^:\s]+\.\w+:\d+: ", line):
            message = re.sub(r"\s+", " ", " ".join(lines[i:i + 3])).strip()
            return f" — {message[:200]}"
    return ""


def compute_one(src: Path, main: str, engine: str, root: Path,
                index: dict[str, str]) -> tuple[list[str] | None, str]:
    """Compile *src* in a throwaway copy. Returns (packages or None, detail)."""
    if not (src / main).exists():
        return None, f"missing {main}"

    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / src.name
        shutil.copytree(src, work, ignore=shutil.ignore_patterns("build"))
        try:
            subprocess.run(
                latexmk_command(engine, main),
                cwd=work,
                capture_output=True,
                timeout=PER_TEMPLATE_TIMEOUT,
            )
        except subprocess.TimeoutExpired:
            pass

        stem = Path(main).stem
        build_dir = work / "build"
        if not (build_dir / f"{stem}.pdf").exists():
            return None, "no PDF produced" + first_error(build_dir / f"{stem}.log")
        if not (build_dir / f"{stem}.fls").exists():
            return None, "latexmk did not write a .fls recorder file"
        return sorted(packages_from_build(build_dir, stem, root, index, engine)), ""


# ---------------------------------------------------------------------------
# latexforge.toml
# ---------------------------------------------------------------------------

def render_block(packages: list[str]) -> str:
    """Render a wrapped TOML array, ~4 names per line for readable diffs."""
    lines = []
    row: list[str] = []
    for name in packages:
        row.append(f'"{name}"')
        if len(", ".join(row)) > 66:
            lines.append("  " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("  " + ", ".join(row) + ",")
    return GENERATED_COMMENT + "tex_packages = [\n" + "\n".join(lines) + "\n]\n"


def write_packages(toml_path: Path, packages: list[str]) -> None:
    """Insert or replace the tex_packages block, keeping every other key."""
    text = toml_path.read_text(encoding="utf-8") if toml_path.exists() else ""
    text = _EXISTING_BLOCK.sub("", text).rstrip()
    block = render_block(packages)
    toml_path.write_text((text + "\n\n" if text else "") + block, encoding="utf-8")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--only", nargs="+", metavar="NAME", help="Only these gallery templates")
    parser.add_argument("--category", help="Only gallery templates in this category")
    parser.add_argument("--path", type=Path, help="Compute for an arbitrary template/project directory instead")
    parser.add_argument("--main", default="main.tex", help="Main file for --path (default: main.tex)")
    parser.add_argument("--engine", choices=sorted(ENGINE_FLAG), help="Engine for --path (default: from latexforge.toml, else lualatex)")
    parser.add_argument("--write", action="store_true", help="Write tex_packages into each template's latexforge.toml")
    parser.add_argument("--json", action="store_true", dest="json_output", help="Print results as JSON")
    args = parser.parse_args()

    for tool in ("latexmk", "kpsewhich"):
        if shutil.which(tool) is None:
            print(f"{tool} not found on PATH — install a full TeX Live first.", file=sys.stderr)
            return 1

    root = texmf_root()
    tlpdb = root / "tlpkg" / "texlive.tlpdb"
    if not tlpdb.exists():
        print(f"No TeX Live package database at {tlpdb} — a TeX Live (not MiKTeX) install is required.", file=sys.stderr)
        return 1
    index = load_file_index(tlpdb)

    jobs: list[tuple[str, Path, str, str]] = []  # (label, dir, main, engine)
    if args.path:
        src = args.path.expanduser().resolve()
        engine = args.engine or read_toml_engine(src / "latexforge.toml")
        jobs.append((src.name, src, args.main, engine))
    else:
        templates = json.loads(GALLERY_JSON.read_text(encoding="utf-8"))["templates"]
        if args.only:
            wanted = set(args.only)
            templates = [t for t in templates if t["name"] in wanted]
        if args.category:
            templates = [t for t in templates if t["category"] == args.category]
        for t in templates:
            jobs.append((t["name"], TEMPLATES_DIR / t["category"] / t["name"], "main.tex", t.get("engine", "lualatex")))

    if not jobs:
        print("No templates matched the selection.")
        return 0

    results: dict[str, list[str]] = {}
    failures: list[tuple[str, str]] = []
    for label, src, main_file, engine in jobs:
        packages, detail = compute_one(src, main_file, engine, root, index)
        if packages is None:
            failures.append((label, detail))
            if not args.json_output:
                print(f"FAIL {label} [{engine}] {detail}", flush=True)
            continue
        results[label] = packages
        if args.write:
            write_packages(src / "latexforge.toml", packages)
        if not args.json_output:
            print(f"ok   {label} [{engine}] {len(packages)} packages", flush=True)

    if args.json_output:
        print(json.dumps(results, indent=2))
    else:
        print("\n" + "=" * 60)
        print(f"  {len(results)}/{len(jobs)} templates analysed" + (" (latexforge.toml updated)" if args.write else ""))
        for label, detail in failures:
            print(f"    FAIL  {label}  {detail}")
        print("=" * 60)
    return 1 if failures else 0


def read_toml_engine(toml_path: Path) -> str:
    """Parse engine from latexforge.toml. Returns 'lualatex' if absent."""
    if not toml_path.exists():
        return "lualatex"
    m = re.search(r'^engine\s*=\s*"([^"]+)"', toml_path.read_text(encoding="utf-8"), re.MULTILINE)
    return m.group(1) if m and m.group(1) in ENGINE_FLAG else "lualatex"


if __name__ == "__main__":
    sys.exit(main())
